"""Writes the final Markdown digest."""
from __future__ import annotations
from datetime import datetime
from typing import List, Dict
import os

SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "UNKNOWN": 4}
SEVERITY_BADGE = {
    "CRITICAL": "[CRITICAL]",
    "HIGH":     "[HIGH]    ",
    "MEDIUM":   "[MEDIUM]  ",
    "LOW":      "[LOW]     ",
    "UNKNOWN":  "[UNKNOWN] ",
}


def write(matches: List[Dict], out_dir: str = "outputs") -> str:
    os.makedirs(out_dir, exist_ok=True)
    today = datetime.now().strftime("%Y-%m-%d")
    path = os.path.join(out_dir, f"digest_{today}.md")

    matches = sorted(
        matches,
        key=lambda m: (
            SEVERITY_ORDER.get((m["advisory"].get("severity") or "UNKNOWN").upper(), 99),
            -m.get("similarity", 0.0),
        ),
    )

    lines: List[str] = []
    lines.append(f"# Security Advisory Digest - {today}")
    lines.append("")
    lines.append(f"**Items affecting your stack:** {len(matches)}")
    lines.append("")
    lines.append("> Generated by the Security Advisory Digest PoC "
                 "(RAG over public feeds + LLM impact judge).")
    lines.append("")

    if not matches:
        lines.append("_No advisories matched your stack today._")
    else:
        # Group by severity for readability
        by_sev: Dict[str, List[Dict]] = {}
        for m in matches:
            sev = (m["advisory"].get("severity") or "UNKNOWN").upper()
            by_sev.setdefault(sev, []).append(m)

        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"]:
            group = by_sev.get(sev) or []
            if not group:
                continue
            lines.append(f"## {SEVERITY_BADGE[sev].strip()} ({len(group)})")
            lines.append("")
            for m in group:
                a = m["advisory"]
                s = m["stack_item"]
                v = m["verdict"]
                lines.append(f"### {a.get('id')} - {a.get('title')}")
                lines.append("")
                lines.append(f"- **Source:** {a.get('source')}")
                lines.append(f"- **Affects:** `{s.get('name')} {s.get('version')}` "
                             f"({s.get('category')})")
                lines.append(f"- **Similarity:** {m.get('similarity', 0):.2f} | "
                             f"**LLM confidence:** {v.confidence:.2f}")
                lines.append(f"- **Impact:** {v.impact}")
                lines.append(f"- **Action:** {v.action}")
                if a.get("url"):
                    lines.append(f"- **Link:** {a.get('url')}")
                lines.append("")

    lines.append("---")
    lines.append(f"_Generated at {datetime.now().isoformat(timespec='seconds')}_")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path
